server:
  port: 1004

#spring 配置
spring:
  http:
    encoding:
      enabled: true
      charset: UTF-8
      force: true

  aop:
    proxy-target-class: true

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 30MB

#zuul配置
zuul:
  add-host-header: true #是否转发主机头
  retryable: false #重试

#注册中心配置
eureka:
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 20   #服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除(默认90秒)
    lease-renewal-interval-in-seconds: 5       #服务刷新时间配置，每隔这个时间会主动心跳一次(默认30秒)
  client:
    service-url:
      defaultZone: http://127.0.0.1:1002/eureka
    registry-fetch-interval-seconds: 10  #重新刷新服务地址的时间